# онфигурация Bandit - исключаем ненужные папки
exclude_dirs:
  - .venv
  - .git
  - __pycache__
  - node_modules

# ропускаем некоторые проверки
skips:
  - B101  # assert used (нужно для тестов)
  - B104  # hardcoded_bind_all_interfaces
